configurationset:
  - configuration:
      name: postgresql_config
      uri: postgresql://ep-rapid-thunder-a2i6xrzm-pooler.eu-central-1.aws.neon.tech/neondb?user=neondb_owner&password=npg_fgF2OyHXp4Cc
